// Auto-generated test vectors - DO NOT EDIT
// Generated by test_vectors.py
// Compatible with Icarus Verilog

localparam NUM_TEST_VECTORS = 8;

// Tile data: 128 bits (16 bytes) per vector
reg [127:0] TILE_DATA [0:NUM_TEST_VECTORS-1];
reg [15:0] EXPECTED_HASH [0:NUM_TEST_VECTORS-1];

// Initialize test vectors
task init_test_vectors;
begin
    TILE_DATA[0] = 128'h00000000000000000000000000000000;  // all_zeros
    TILE_DATA[1] = 128'hFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF;  // all_ones
    TILE_DATA[2] = 128'h000102030405060708090A0B0C0D0E0F;  // sequential
    TILE_DATA[3] = 128'hAA55AA55AA55AA55AA55AA55AA55AA55;  // alternating
    TILE_DATA[4] = 128'hFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF;  // filled_square
    TILE_DATA[5] = 128'h18003C00660066007E00660066000000;  // letter_a
    TILE_DATA[6] = 128'hAD23A8D85C9A4E06559EF6972AEFD571;  // pseudo_random
    TILE_DATA[7] = 128'h80000000000000000000000000000000;  // single_bit

    EXPECTED_HASH[0] = 16'h6A0A;  // all_zeros
    EXPECTED_HASH[1] = 16'h6A4B;  // all_ones
    EXPECTED_HASH[2] = 16'h3B37;  // sequential
    EXPECTED_HASH[3] = 16'h96A6;  // alternating
    EXPECTED_HASH[4] = 16'h6A4B;  // filled_square
    EXPECTED_HASH[5] = 16'h17AA;  // letter_a
    EXPECTED_HASH[6] = 16'hA49B;  // pseudo_random
    EXPECTED_HASH[7] = 16'h627B;  // single_bit
end
endtask

// Get test name by index
function [127:0] get_test_name;
    input integer idx;
    begin
        case (idx)
            0: get_test_name = "all_zeros       ";
            1: get_test_name = "all_ones        ";
            2: get_test_name = "sequential      ";
            3: get_test_name = "alternating     ";
            4: get_test_name = "filled_square   ";
            5: get_test_name = "letter_a        ";
            6: get_test_name = "pseudo_random   ";
            7: get_test_name = "single_bit      ";
            default: get_test_name = "unknown         ";
        endcase
    end
endfunction
